name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.5' # Matches the error log
          cache: 'pnpm' # Cache pnpm dependencies

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '8.15.1' # Stable version; adjust based on package.json
          run_install: false # Prevent automatic pnpm install here

      - name: Verify pnpm installation
        run: |
          which pnpm
          pnpm --version
        shell: bash

      - name: Install dependencies
        run: pnpm install

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MOSS_069E6C200 }}
          action: 'upload'
          ###### Repository/Build Configurations ######
          app_location: '/' # App source code path (root)
          api_location: 'api' # API source code path (assumes proxy.ts is in /api)
          output_location: 'build' # Built app content directory
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MOSS_069E6C200 }}
          action: 'close'
